name: Deploy to GitHub Pages

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Deploy storybook to Github Pages
        run: npm run deploy-storybook --branch gh-pages -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

