name: Deploy to GitHub Pages

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      # - name: Deploy storybook to Github Pages
      #   run: npm run deploy-storybook --branch gh-pages -- --ci
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Deploy storybook to Github Pages
        uses: deborah-digges/deploy-storybook-action@v11.0
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

